url: https://y7kim.github.io
baseurl: /vinylhead/

# Site settings
title: TH'OVEN
email: thoven.booking@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Alexandre Sequeira
  pic: 1
  position: Music producer and DJ


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/live.thoven/
  - title: instagram
    url: https://www.instagram.com/th.oven/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty